### ISSUE TITLE
url paths?

### ISSUE THREAD

**Issue by hansbak** [felangel/flow_builder#20]
New navigator has the ability to request certain url paths....how does this work with flow builder?

thanks for the excellent open source contributions!
Regards,
Hans

**Comment by hansbak** [comment]
You are so much ahead of my knowledge, at the moment i am still working on the best way implementing your Bloc combined with infinite scrolling, authorization and the best number of blocs together with the communication between them....blocs for Authorization, products,categories,orders, leads,customers suppliers etc.....All in my GrowERP project. 

So now hoping you can simplify routing because version 2 is too difficult for me and web is important, therefore the paths request....

Keep up the good work, but not make things too difficult.
An example is your infinite scrolling, the [doc](https://github.com/felangel/bloc/blob/master/docs/flutterinfinitelisttutorial.md) tutorial explains a much easier to understand implementation than the [example implementation](https://github.com/felangel/bloc/tree/master/examples/flutter_infinite_list).

**Comment by LucaDillenburg** [comment]
I totally agree with @hansbak . That's really important to have in order to improve the support for the web.

The way I saw other packages implementing this is by incorporating default named routes into the package (for example the [```vrouter``` package](https://pub.dev/packages/vrouter)). This works, but I think it adds unnecessary parser logic and complicates things (especially for apps that are only for iOS and Android).

What I think it's a better solution though would be to add as an optional implementation for those that want either named parameters and/or web support in a way that maintains the code the same in ```.flow``` calls and changed only the onGenerateRoute by adding something like a URL parser that returned the flow state data.

I would love to hear your thoughts and please tell me if there's something I wasn't clear on.

**Comment by felangel** [comment]
Proposal to add routing support can be found at https://github.com/felangel/flow_builder/issues/41.

**Comment by hansbak** [comment]
Excellent @felangel , thank you very much for your good work.....very much appreciated!

**Comment by felangel** [comment]
Closing in favor of #41 👍
